// <auto-generated />
namespace ApplicationCore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class Product__UnitPrice__Added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Product__UnitPrice__Added));
        
        string IMigrationMetadata.Id
        {
            get { return "202101020745359_Product__UnitPrice__Added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
